directives:
- add_directives:
    file: package://manipulation/iiwa_and_wsg.dmd.yaml
- add_model:
    name: bin0
    file: /work/manipulation/project/Crust_&_Conquer_PizzaBot/Object/bin.sdf
- add_weld:
    parent: world
    child: bin0::bin_base
    X_PC:
      rotation: !Rpy {{ deg: [0.0, 0.0, 180.0 ]}}
      translation: [-0.05, -0.5, -0.015]



