directives:
- add_directives:
    file: package://manipulation/iiwa_and_wsg.dmd.yaml
- add_model:
    name: bin0
    file: /work/manipulation/project/Object/bin.sdf
- add_weld:
    parent: world
    child: bin0::bin_base
    X_PC:
      translation: [-0.05, -0.5, -0.015]



